### ISSUE TITLE
Add locking statements 

### ISSUE THREAD

**Issue by HenryRLee** [Click-to-Cloud/Query.apex#25]
https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_locking_statements.htm

https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_for_view.htm

For example the 'FOR UPDATE' keyword.

**Comment by HenryRLee** [comment]
More specifically, we can add a public method named `forUpdate`, `forView`, etc. When these methods are called, respective `FOR UPDATE` or `FOR VIEW` keywords are added to the query.

**Comment by coderdecoder01** [comment]
Would like to work on this one. Wondering if it will be counted towards Hacktoberfest contribution

**Comment by HenryRLee** [comment]
Hi, @coderdecoder01. It would be certainly counted. Have fun coding!

**Comment by HenryRLee** [comment]
Fixed in #35
